sources:
  include:
    - Sources/Core
templates:
  include:
    - Sources/Core/CodeGeneration/Templates
  exclude:
    - Sources/Core/CodeGeneration/Templates/AutoCases.stencil
    - Sources/Core/CodeGeneration/Templates/AutoEquatable.stencil
    - Sources/Core/CodeGeneration/Templates/AutoHashable.stencil
    - Sources/Core/CodeGeneration/Templates/AutoLenses.stencil

output: Sources/Core/CodeGeneration
