osx_image: xcode9.3
language: objective-c
xcode_project: SwiftRex.xcodeproj
xcode_scheme: SwiftRex iOS
cache:
  directories:
  - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated swiftlint || brew upgrade swiftlint
  - brew outdated sourcery || brew upgrade sourcery
  - carthage bootstrap --verbose --no-use-binaries --cache-builds